'use client';

import { UnifiedReport } from './report-service';
import { AIVerdict } from './gemini';

interface PDFOptions {
    report: UnifiedReport;
    verdict?: AIVerdict | null;
    locale: string;
}

const LABELS: Record<string, Record<string, string>> = {
    ro: {
        title: 'Raport Oficial VYN.md',
        subtitle: 'Raport de Verificare Autovehicul',
        vin: 'Cod VIN',
        generated: 'Generat la',
        specs: 'Specificații Tehnice',
        national: 'Date Registru Național (RM)',
        history: 'Istoricul Vehiculului',
        aiVerdict: 'Verdict AI — VYN Consultant',
        rating: 'Evaluare',
        confidence: 'Încredere în date',
        recommendation: 'Recomandare',
        keyPoints: 'Puncte cheie',
        noNational: 'Vehiculul nu este înregistrat în baza de date RM.',
        noHistory: 'Nu există evenimente înregistrate.',
        green: '🟢 SIGUR',
        yellow: '🟡 NECESITĂ VERIFICARE',
        red: '🔴 EVITAȚI',
        footer: 'Raport generat de VYN.md • vyn-three.vercel.app • Toate drepturile rezervate',
        inspections: 'Inspecții Tehnice',
        border: 'Treceri Frontieră',
        status: 'Status',
        mileage: 'Kilometraj',
        date: 'Data',
        result: 'Rezultat',
        point: 'Punct',
        direction: 'Direcție',
        entry: 'Intrare',
        exit: 'Ieșire',
    },
    en: {
        title: 'VYN.md Official Report',
        subtitle: 'Vehicle History Report',
        vin: 'VIN Code',
        generated: 'Generated on',
        specs: 'Technical Specifications',
        national: 'National Registry Data (MD)',
        history: 'Vehicle History',
        aiVerdict: 'AI Verdict — VYN Consultant',
        rating: 'Rating',
        confidence: 'Data Confidence',
        recommendation: 'Recommendation',
        keyPoints: 'Key Points',
        noNational: 'Vehicle not found in MD national registry.',
        noHistory: 'No recorded events found.',
        green: '🟢 SAFE',
        yellow: '🟡 NEEDS INSPECTION',
        red: '🔴 AVOID',
        footer: 'Report generated by VYN.md • vyn-three.vercel.app • All rights reserved',
        inspections: 'Technical Inspections',
        border: 'Border Crossings',
        status: 'Status',
        mileage: 'Mileage',
        date: 'Date',
        result: 'Result',
        point: 'Point',
        direction: 'Direction',
        entry: 'Entry',
        exit: 'Exit',
    },
    ru: {
        title: 'Официальный отчёт VYN.md',
        subtitle: 'Отчёт о проверке автомобиля',
        vin: 'VIN-код',
        generated: 'Создан',
        specs: 'Технические характеристики',
        national: 'Данные национального реестра (РМ)',
        history: 'История автомобиля',
        aiVerdict: 'Вердикт ИИ — VYN Консультант',
        rating: 'Оценка',
        confidence: 'Достоверность данных',
        recommendation: 'Рекомендация',
        keyPoints: 'Ключевые моменты',
        noNational: 'Автомобиль не найден в реестре РМ.',
        noHistory: 'Зарегистрированных событий нет.',
        green: '🟢 БЕЗОПАСНО',
        yellow: '🟡 ТРЕБУЕТ ПРОВЕРКИ',
        red: '🔴 ИЗБЕГАЙТЕ',
        footer: 'Отчёт создан VYN.md • vyn-three.vercel.app • Все права защищены',
        inspections: 'Технические осмотры',
        border: 'Пересечения границы',
        status: 'Статус',
        mileage: 'Пробег',
        date: 'Дата',
        result: 'Результат',
        point: 'Пункт',
        direction: 'Направление',
        entry: 'Въезд',
        exit: 'Выезд',
    },
};

function getLabel(locale: string, key: string): string {
    const lang = LABELS[locale] || LABELS['ro'];
    return lang[key] || LABELS['ro'][key] || key;
}

function getRatingLabel(locale: string, rating: 'green' | 'yellow' | 'red'): string {
    return getLabel(locale, rating);
}

export async function generatePDFReport({ report, verdict, locale }: PDFOptions): Promise<void> {
    // Dynamic import to avoid SSR issues
    const jsPDF = (await import('jspdf')).default;

    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const pageW = 210;
    const pageH = 297;
    const margin = 18;
    const contentW = pageW - margin * 2;
    let y = 0;

    const L = (key: string) => getLabel(locale, key);

    // ── Colors ──────────────────────────────────────────────
    const BLUE = [37, 99, 235] as [number, number, number];
    const DARK = [15, 23, 42] as [number, number, number];
    const GRAY = [100, 116, 139] as [number, number, number];
    const LIGHT = [248, 250, 252] as [number, number, number];
    const WHITE: [number, number, number] = [255, 255, 255];
    const GREEN = [16, 185, 129] as [number, number, number];
    const YELLOW = [245, 158, 11] as [number, number, number];
    const RED = [239, 68, 68] as [number, number, number];

    function addPage() {
        doc.addPage();
        y = margin;
        // Page footer
        doc.setFontSize(7);
        doc.setTextColor(...GRAY);
        doc.text(L('footer'), pageW / 2, pageH - 8, { align: 'center' });
        doc.text(`${report.vin}`, margin, pageH - 8);
    }

    function checkPageBreak(needed: number) {
        if (y + needed > pageH - 20) {
            addPage();
        }
    }

    function sectionHeader(title: string, color: [number, number, number] = BLUE) {
        checkPageBreak(14);
        doc.setFillColor(...color);
        doc.roundedRect(margin, y, contentW, 10, 2, 2, 'F');
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...WHITE);
        doc.text(title.toUpperCase(), margin + 4, y + 6.5);
        y += 14;
    }

    function row(label: string, value: string, shade = false) {
        checkPageBreak(8);
        if (shade) {
            doc.setFillColor(...LIGHT);
            doc.rect(margin, y, contentW, 7, 'F');
        }
        doc.setFontSize(8);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...GRAY);
        doc.text(label, margin + 3, y + 4.5);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...DARK);
        doc.text(String(value), margin + 70, y + 4.5);
        y += 7;
    }

    // ══════════════════════════════════════════════════════════
    // HEADER
    // ══════════════════════════════════════════════════════════
    doc.setFillColor(...DARK);
    doc.rect(0, 0, pageW, 50, 'F');

    // Blue accent bar
    doc.setFillColor(...BLUE);
    doc.rect(0, 0, 6, 50, 'F');

    // Logo text
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...WHITE);
    doc.text('VYN.md', margin, 20);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184);
    doc.text(L('subtitle').toUpperCase(), margin, 28);

    // VIN badge
    doc.setFillColor(...BLUE);
    doc.roundedRect(margin, 33, contentW, 11, 2, 2, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...WHITE);
    doc.text(`${L('vin')}: ${report.vin}`, margin + 4, 40.5);

    // Date top-right
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184);
    const dateStr = new Date().toLocaleDateString(locale === 'ru' ? 'ru-RU' : locale === 'en' ? 'en-GB' : 'ro-RO', {
        day: '2-digit', month: 'long', year: 'numeric'
    });
    doc.text(`${L('generated')}: ${dateStr}`, pageW - margin, 12, { align: 'right' });

    y = 58;

    // ══════════════════════════════════════════════════════════
    // VEHICLE IDENTITY
    // ══════════════════════════════════════════════════════════
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...DARK);
    doc.text(`${report.year} ${report.make} ${report.model}`, margin, y);
    y += 10;

    // ══════════════════════════════════════════════════════════
    // AI VERDICT
    // ══════════════════════════════════════════════════════════
    if (verdict) {
        checkPageBreak(50);
        const verdictColor = verdict.rating === 'green' ? GREEN : verdict.rating === 'red' ? RED : YELLOW;
        const verdictLabel = getRatingLabel(locale, verdict.rating);

        doc.setFillColor(...verdictColor);
        doc.roundedRect(margin, y, contentW, 40, 3, 3, 'F');

        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...WHITE);
        doc.text(L('aiVerdict'), margin + 5, y + 9);

        doc.setFontSize(14);
        doc.text(verdictLabel, margin + 5, y + 19);

        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        const summaryLines = doc.splitTextToSize(verdict.summary, contentW - 10);
        doc.text(summaryLines.slice(0, 2), margin + 5, y + 27);

        doc.setFont('helvetica', 'bold');
        doc.text(`${L('confidence')}: ${verdict.confidence}%`, pageW - margin - 5, y + 9, { align: 'right' });

        y += 46;
    }

    // ══════════════════════════════════════════════════════════
    // SPECS
    // ══════════════════════════════════════════════════════════
    sectionHeader(L('specs'));
    const specsEntries = Object.entries(report.specs);
    specsEntries.forEach(([key, value], i) => {
        row(key, String(value), i % 2 === 0);
    });
    y += 4;

    // ══════════════════════════════════════════════════════════
    // NATIONAL DATA
    // ══════════════════════════════════════════════════════════
    checkPageBreak(20);
    sectionHeader(L('national'), [5, 150, 105]);

    if (report.nationalData) {
        const v = report.nationalData.vehicle;
        if (v) {
            row(L('status'), v.Status || 'N/A', true);
            row('Marca', v.Brand || 'N/A', false);
            row('Model', v.Model || 'N/A', true);
            row('Culoare', v.Color || 'N/A', false);
        }

        if (report.nationalData.inspections?.length > 0) {
            y += 4;
            checkPageBreak(10);
            doc.setFontSize(8);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(...GRAY);
            doc.text(L('inspections').toUpperCase(), margin, y);
            y += 5;

            report.nationalData.inspections.forEach((ins: any, i: number) => {
                row(ins.Date, `${ins.Result} — ${ins.Mileage} km`, i % 2 === 0);
            });
        }

        if (report.nationalData.borderCrossings?.length > 0) {
            y += 4;
            checkPageBreak(10);
            doc.setFontSize(8);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(...GRAY);
            doc.text(L('border').toUpperCase(), margin, y);
            y += 5;

            report.nationalData.borderCrossings.forEach((b: any, i: number) => {
                const dir = b.Direction === 'ENTRY' ? L('entry') : L('exit');
                row(b.DateTime?.split(' ')[0] || '', `${b.Point} — ${dir}`, i % 2 === 0);
            });
        }
    } else {
        checkPageBreak(10);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'italic');
        doc.setTextColor(...GRAY);
        doc.text(L('noNational'), margin + 3, y + 4);
        y += 10;
    }

    // ══════════════════════════════════════════════════════════
    // AI KEY POINTS & RECOMMENDATION
    // ══════════════════════════════════════════════════════════
    if (verdict && verdict.keyPoints?.length > 0) {
        checkPageBreak(30);
        sectionHeader(L('keyPoints'), [99, 102, 241]);

        verdict.keyPoints.forEach((point, i) => {
            checkPageBreak(8);
            doc.setFontSize(8);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(...DARK);
            if (i % 2 === 0) {
                doc.setFillColor(...LIGHT);
                doc.rect(margin, y, contentW, 7, 'F');
            }
            doc.text(`• ${point}`, margin + 3, y + 4.5, { maxWidth: contentW - 6 });
            y += 7;
        });

        y += 4;
        checkPageBreak(16);
        doc.setFillColor(239, 246, 255);
        doc.roundedRect(margin, y, contentW, 14, 2, 2, 'F');
        doc.setFontSize(8);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...BLUE);
        doc.text(L('recommendation').toUpperCase() + ':', margin + 4, y + 5.5);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...DARK);
        const recLines = doc.splitTextToSize(verdict.recommendation, contentW - 8);
        doc.text(recLines.slice(0, 2), margin + 4, y + 10.5);
        y += 18;
    }

    // ══════════════════════════════════════════════════════════
    // HISTORY
    // ══════════════════════════════════════════════════════════
    if (report.history.length > 0) {
        checkPageBreak(20);
        sectionHeader(L('history'), [71, 85, 105]);

        report.history.forEach((event: any, i: number) => {
            checkPageBreak(8);
            if (i % 2 === 0) {
                doc.setFillColor(...LIGHT);
                doc.rect(margin, y, contentW, 7, 'F');
            }
            doc.setFontSize(7.5);
            doc.setFont('helvetica', 'bold');
            doc.setTextColor(...GRAY);
            doc.text(event.date || '', margin + 3, y + 4.5);
            doc.setFont('helvetica', 'normal');
            doc.setTextColor(...DARK);
            doc.text(event.description || '', margin + 35, y + 4.5, { maxWidth: contentW - 38 });
            y += 7;
        });
    }

    // ══════════════════════════════════════════════════════════
    // FOOTER on last page
    // ══════════════════════════════════════════════════════════
    doc.setFontSize(7);
    doc.setTextColor(...GRAY);
    doc.text(L('footer'), pageW / 2, pageH - 8, { align: 'center' });
    doc.text(report.vin, margin, pageH - 8);

    // Save
    const fileName = `VYN-Report-${report.vin}-${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
}
