'use client';

import { UnifiedReport } from './report-service';
import { AIVerdict } from './gemini';

interface PDFOptions {
    report: UnifiedReport;
    verdict?: AIVerdict | null;
    locale: string;
}

const LABELS: Record<string, Record<string, string>> = {
    ro: {
        subtitle: 'Raport de Verificare Autovehicul',
        vin: 'Cod VIN',
        generated: 'Generat la',
        specs: 'Specificații Tehnice',
        national: 'Date Registru Național (RM)',
        history: 'Istoricul Vehiculului',
        aiVerdict: 'Verdict AI — VYN Consultant',
        confidence: 'Încredere în date',
        recommendation: 'Recomandare',
        keyPoints: 'Puncte Cheie',
        noNational: 'Vehiculul nu este înregistrat în baza de date RM.',
        noHistory: 'Nu există evenimente înregistrate.',
        green: '🟢 SIGUR',
        yellow: '🟡 NECESITĂ VERIFICARE',
        red: '🔴 EVITAȚI',
        footer: 'Raport generat de VYN.md • vyn-three.vercel.app • Toate drepturile rezervate',
        inspections: 'Inspecții Tehnice',
        border: 'Treceri Frontieră',
        entry: 'Intrare',
        exit: 'Ieșire',
        noData: 'Date indisponibile',
    },
    en: {
        subtitle: 'Vehicle History Report',
        vin: 'VIN Code',
        generated: 'Generated on',
        specs: 'Technical Specifications',
        national: 'National Registry Data (MD)',
        history: 'Vehicle History',
        aiVerdict: 'AI Verdict — VYN Consultant',
        confidence: 'Data Confidence',
        recommendation: 'Recommendation',
        keyPoints: 'Key Points',
        noNational: 'Vehicle not found in MD national registry.',
        noHistory: 'No recorded events found.',
        green: '🟢 SAFE',
        yellow: '🟡 NEEDS INSPECTION',
        red: '🔴 AVOID',
        footer: 'Report generated by VYN.md • vyn-three.vercel.app • All rights reserved',
        inspections: 'Technical Inspections',
        border: 'Border Crossings',
        entry: 'Entry',
        exit: 'Exit',
        noData: 'Data unavailable',
    },
    ru: {
        subtitle: 'Отчёт о проверке автомобиля',
        vin: 'VIN-код',
        generated: 'Создан',
        specs: 'Технические характеристики',
        national: 'Данные национального реестра (РМ)',
        history: 'История автомобиля',
        aiVerdict: 'Вердикт ИИ — VYN Консультант',
        confidence: 'Достоверность данных',
        recommendation: 'Рекомендация',
        keyPoints: 'Ключевые моменты',
        noNational: 'Автомобиль не найден в реестре РМ.',
        noHistory: 'Зарегистрированных событий нет.',
        green: '🟢 БЕЗОПАСНО',
        yellow: '🟡 ТРЕБУЕТ ПРОВЕРКИ',
        red: '🔴 ИЗБЕГАЙТЕ',
        footer: 'Отчёт создан VYN.md • vyn-three.vercel.app • Все права защищены',
        inspections: 'Технические осмотры',
        border: 'Пересечения границы',
        entry: 'Въезд',
        exit: 'Выезд',
        noData: 'Данные недоступны',
    },
};

function L(locale: string, key: string): string {
    return (LABELS[locale] || LABELS['ro'])[key] || (LABELS['ro'])[key] || key;
}

function getRatingColor(rating: string): { bg: string; text: string; border: string; label: string } {
    switch (rating) {
        case 'green': return { bg: '#064e3b', text: '#34d399', border: '#10b981', label: '✓ SIGUR' };
        case 'red': return { bg: '#450a0a', text: '#f87171', border: '#ef4444', label: '✗ EVITAȚI' };
        default: return { bg: '#451a03', text: '#fbbf24', border: '#f59e0b', label: '⚠ VERIFICARE' };
    }
}

function buildHTML(report: UnifiedReport, verdict: AIVerdict | null | undefined, locale: string): string {
    const dateStr = new Date().toLocaleDateString(
        locale === 'ru' ? 'ru-RU' : locale === 'en' ? 'en-GB' : 'ro-RO',
        { day: '2-digit', month: 'long', year: 'numeric' }
    );

    const ratingCfg = verdict ? getRatingColor(verdict.rating) : getRatingColor('yellow');
    const ratingLabel = verdict ? (
        verdict.rating === 'green' ? L(locale, 'green') :
            verdict.rating === 'red' ? L(locale, 'red') : L(locale, 'yellow')
    ) : L(locale, 'yellow');

    const specsRows = Object.entries(report.specs).map(([k, v], i) => `
        <tr style="background:${i % 2 === 0 ? '#f8fafc' : '#ffffff'}">
            <td style="padding:10px 16px;font-weight:700;color:#64748b;font-size:12px;width:45%">${k}</td>
            <td style="padding:10px 16px;font-weight:600;color:#0f172a;font-size:13px">${v}</td>
        </tr>`).join('');

    const inspectionRows = report.nationalData?.inspections?.map((ins: any, i: number) => `
        <tr style="background:${i % 2 === 0 ? '#f0fdf4' : '#ffffff'}">
            <td style="padding:8px 14px;font-size:12px;color:#374151">${ins.Date || ''}</td>
            <td style="padding:8px 14px;font-size:12px;color:#374151">${ins.Result || ''}</td>
            <td style="padding:8px 14px;font-size:12px;color:#374151">${ins.Mileage ? ins.Mileage + ' km' : ''}</td>
        </tr>`).join('') || '';

    const borderRows = report.nationalData?.borderCrossings?.map((b: any, i: number) => `
        <tr style="background:${i % 2 === 0 ? '#f0fdf4' : '#ffffff'}">
            <td style="padding:8px 14px;font-size:12px;color:#374151">${b.DateTime?.split(' ')[0] || ''}</td>
            <td style="padding:8px 14px;font-size:12px;color:#374151">${b.Point || ''}</td>
            <td style="padding:8px 14px;font-size:12px;color:#374151">${b.Direction === 'ENTRY' ? L(locale, 'entry') : L(locale, 'exit')}</td>
        </tr>`).join('') || '';

    const historyItems = report.history.slice(0, 12).map((ev: any, i: number) => `
        <div style="display:flex;gap:16px;padding:10px 0;border-bottom:1px solid #e2e8f0;align-items:flex-start">
            <div style="min-width:90px;font-size:11px;font-weight:700;color:#64748b;padding-top:2px">${ev.date || ''}</div>
            <div style="flex:1">
                <span style="display:inline-block;padding:2px 8px;border-radius:20px;font-size:10px;font-weight:800;letter-spacing:0.05em;margin-bottom:4px;background:${ev.type === 'INSPECȚIE' ? '#dcfce7' : ev.type === 'FRONTIERĂ' ? '#dbeafe' : '#fef9c3'};color:${ev.type === 'INSPECȚIE' ? '#166534' : ev.type === 'FRONTIERĂ' ? '#1e40af' : '#854d0e'}">${ev.type}</span>
                <div style="font-size:12px;color:#374151;font-weight:500">${ev.description || ''}</div>
            </div>
        </div>`).join('');

    const keyPointsHTML = verdict?.keyPoints?.map(p => `
        <div style="display:flex;gap:10px;padding:8px 0;border-bottom:1px solid rgba(255,255,255,0.1);align-items:flex-start">
            <div style="width:6px;height:6px;border-radius:50%;background:${ratingCfg.border};margin-top:5px;flex-shrink:0"></div>
            <p style="margin:0;font-size:13px;color:rgba(255,255,255,0.85);line-height:1.5">${p}</p>
        </div>`).join('') || '';

    return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif; background: #ffffff; color: #0f172a; width: 794px; }
  .page { width: 794px; padding: 0; }
</style>
</head>
<body>
<div class="page">

  <!-- HEADER -->
  <div style="background:linear-gradient(135deg,#0f172a 0%,#1e3a5f 100%);padding:40px 48px 32px;position:relative;overflow:hidden">
    <div style="position:absolute;left:0;top:0;bottom:0;width:6px;background:#2563eb"></div>
    <div style="display:flex;justify-content:space-between;align-items:flex-start">
      <div>
        <div style="display:flex;align-items:center;gap:12px;margin-bottom:8px">
          <div style="width:40px;height:40px;background:#2563eb;border-radius:10px;display:flex;align-items:center;justify-content:center;font-weight:900;font-style:italic;color:white;font-size:18px">V</div>
          <div>
            <div style="font-size:20px;font-weight:900;color:white;letter-spacing:-0.5px">VYN.md</div>
            <div style="font-size:9px;font-weight:700;color:#94a3b8;letter-spacing:0.2em;text-transform:uppercase">${L(locale, 'subtitle')}</div>
          </div>
        </div>
      </div>
      <div style="text-align:right">
        <div style="font-size:10px;font-weight:600;color:#64748b;text-transform:uppercase;letter-spacing:0.1em">${L(locale, 'generated')}</div>
        <div style="font-size:13px;font-weight:700;color:#94a3b8;margin-top:2px">${dateStr}</div>
      </div>
    </div>

    <!-- Vehicle Title -->
    <div style="margin-top:24px">
      <div style="font-size:32px;font-weight:900;color:white;letter-spacing:-1px;line-height:1">${report.year} ${report.make} ${report.model}</div>
      <div style="margin-top:12px;background:rgba(37,99,235,0.3);border:1px solid rgba(37,99,235,0.5);border-radius:10px;padding:10px 16px;display:inline-block">
        <span style="font-size:10px;font-weight:700;color:#93c5fd;text-transform:uppercase;letter-spacing:0.15em">${L(locale, 'vin')}: </span>
        <span style="font-size:14px;font-weight:800;color:white;letter-spacing:0.05em;font-family:monospace">${report.vin}</span>
      </div>
    </div>
  </div>

  <div style="padding:32px 48px">

    <!-- AI VERDICT -->
    ${verdict ? `
    <div style="background:${ratingCfg.bg};border:1px solid ${ratingCfg.border};border-radius:20px;padding:24px 28px;margin-bottom:28px">
      <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:14px">
        <div>
          <div style="font-size:10px;font-weight:700;color:rgba(255,255,255,0.4);text-transform:uppercase;letter-spacing:0.2em;margin-bottom:6px">✦ ${L(locale, 'aiVerdict')}</div>
          <div style="font-size:22px;font-weight:900;color:${ratingCfg.text};letter-spacing:-0.5px">${ratingLabel}</div>
        </div>
        <div style="text-align:right">
          <div style="font-size:10px;font-weight:700;color:rgba(255,255,255,0.4);text-transform:uppercase;letter-spacing:0.1em">${L(locale, 'confidence')}</div>
          <div style="font-size:28px;font-weight:900;color:${ratingCfg.text}">${verdict.confidence}%</div>
        </div>
      </div>
      <p style="font-size:13px;color:rgba(255,255,255,0.75);line-height:1.6;margin-bottom:${verdict.keyPoints?.length ? '16px' : '0'}">${verdict.summary}</p>
      ${verdict.keyPoints?.length ? `
      <div style="border-top:1px solid rgba(255,255,255,0.1);padding-top:14px">
        <div style="font-size:10px;font-weight:800;color:rgba(255,255,255,0.35);text-transform:uppercase;letter-spacing:0.2em;margin-bottom:10px">${L(locale, 'keyPoints')}</div>
        ${keyPointsHTML}
      </div>` : ''}
      ${verdict.recommendation ? `
      <div style="margin-top:16px;background:rgba(255,255,255,0.08);border-radius:12px;padding:14px 16px">
        <div style="font-size:10px;font-weight:800;color:rgba(255,255,255,0.35);text-transform:uppercase;letter-spacing:0.2em;margin-bottom:6px">${L(locale, 'recommendation')}</div>
        <p style="font-size:13px;font-weight:600;color:white;line-height:1.5">${verdict.recommendation}</p>
      </div>` : ''}
    </div>` : ''}

    <!-- SPECS -->
    <div style="margin-bottom:28px">
      <div style="background:#2563eb;border-radius:12px;padding:12px 18px;margin-bottom:2px">
        <div style="font-size:11px;font-weight:800;color:white;text-transform:uppercase;letter-spacing:0.15em">${L(locale, 'specs')}</div>
      </div>
      <table style="width:100%;border-collapse:collapse;border-radius:0 0 12px 12px;overflow:hidden">
        ${specsRows}
      </table>
    </div>

    <!-- NATIONAL DATA -->
    <div style="margin-bottom:28px">
      <div style="background:#059669;border-radius:12px;padding:12px 18px;margin-bottom:2px">
        <div style="font-size:11px;font-weight:800;color:white;text-transform:uppercase;letter-spacing:0.15em">${L(locale, 'national')}</div>
      </div>
      ${report.nationalData ? `
        ${report.nationalData.vehicle ? `
        <table style="width:100%;border-collapse:collapse;margin-bottom:12px">
          ${['Status', 'Brand', 'Model', 'Color'].filter(k => report.nationalData.vehicle[k]).map((k, i) => `
          <tr style="background:${i % 2 === 0 ? '#f0fdf4' : '#ffffff'}">
            <td style="padding:9px 16px;font-weight:700;color:#64748b;font-size:12px;width:45%">${k}</td>
            <td style="padding:9px 16px;font-weight:600;color:#0f172a;font-size:13px">${report.nationalData.vehicle[k]}</td>
          </tr>`).join('')}
        </table>` : ''}

        ${inspectionRows ? `
        <div style="font-size:10px;font-weight:800;color:#64748b;text-transform:uppercase;letter-spacing:0.15em;padding:10px 0 6px">${L(locale, 'inspections')}</div>
        <table style="width:100%;border-collapse:collapse">
          <tr style="background:#dcfce7">
            <th style="padding:8px 14px;text-align:left;font-size:10px;font-weight:800;color:#166534;text-transform:uppercase;letter-spacing:0.1em">Data</th>
            <th style="padding:8px 14px;text-align:left;font-size:10px;font-weight:800;color:#166534;text-transform:uppercase;letter-spacing:0.1em">Rezultat</th>
            <th style="padding:8px 14px;text-align:left;font-size:10px;font-weight:800;color:#166534;text-transform:uppercase;letter-spacing:0.1em">Km</th>
          </tr>
          ${inspectionRows}
        </table>` : ''}

        ${borderRows ? `
        <div style="font-size:10px;font-weight:800;color:#64748b;text-transform:uppercase;letter-spacing:0.15em;padding:14px 0 6px">${L(locale, 'border')}</div>
        <table style="width:100%;border-collapse:collapse">
          <tr style="background:#dbeafe">
            <th style="padding:8px 14px;text-align:left;font-size:10px;font-weight:800;color:#1e40af;text-transform:uppercase;letter-spacing:0.1em">Data</th>
            <th style="padding:8px 14px;text-align:left;font-size:10px;font-weight:800;color:#1e40af;text-transform:uppercase;letter-spacing:0.1em">Punct</th>
            <th style="padding:8px 14px;text-align:left;font-size:10px;font-weight:800;color:#1e40af;text-transform:uppercase;letter-spacing:0.1em">Direcție</th>
          </tr>
          ${borderRows}
        </table>` : ''}
      ` : `<p style="padding:16px;font-size:13px;color:#64748b;font-style:italic">${L(locale, 'noNational')}</p>`}
    </div>

    <!-- HISTORY -->
    ${report.history.length > 0 ? `
    <div style="margin-bottom:28px">
      <div style="background:#475569;border-radius:12px;padding:12px 18px;margin-bottom:12px">
        <div style="font-size:11px;font-weight:800;color:white;text-transform:uppercase;letter-spacing:0.15em">${L(locale, 'history')}</div>
      </div>
      ${historyItems}
    </div>` : ''}

  </div>

  <!-- FOOTER -->
  <div style="background:#0f172a;padding:16px 48px;display:flex;justify-content:space-between;align-items:center">
    <div style="font-size:10px;font-weight:700;color:#475569;font-family:monospace">${report.vin}</div>
    <div style="font-size:10px;color:#475569;font-weight:500">${L(locale, 'footer')}</div>
  </div>

</div>
</body>
</html>`;
}

export async function generatePDFReport({ report, verdict, locale }: PDFOptions): Promise<void> {
    const [jsPDFModule, html2canvasModule] = await Promise.all([
        import('jspdf'),
        import('html2canvas'),
    ]);
    const jsPDF = jsPDFModule.default;
    const html2canvas = html2canvasModule.default;

    // Create hidden iframe to render HTML
    const iframe = document.createElement('iframe');
    iframe.style.cssText = 'position:fixed;top:-9999px;left:-9999px;width:794px;height:auto;border:none;visibility:hidden';
    document.body.appendChild(iframe);

    const html = buildHTML(report, verdict, locale);
    iframe.contentDocument!.open();
    iframe.contentDocument!.write(html);
    iframe.contentDocument!.close();

    // Wait for fonts and images to load
    await new Promise(resolve => setTimeout(resolve, 1500));

    const container = iframe.contentDocument!.body;

    const canvas = await html2canvas(container, {
        scale: 2,
        useCORS: true,
        allowTaint: true,
        backgroundColor: '#ffffff',
        width: 794,
        windowWidth: 794,
        logging: false,
    });

    document.body.removeChild(iframe);

    const imgData = canvas.toDataURL('image/jpeg', 0.95);
    const imgWidth = 210; // A4 mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    const doc = new jsPDF({
        orientation: imgHeight > 297 ? 'portrait' : 'portrait',
        unit: 'mm',
        format: 'a4',
    });

    // Split into A4 pages if content is taller
    const pageHeight = 297;
    let position = 0;
    let remainingHeight = imgHeight;

    doc.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);

    while (remainingHeight > pageHeight) {
        position -= pageHeight;
        remainingHeight -= pageHeight;
        doc.addPage();
        doc.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight);
    }

    const fileName = `VYN-Report-${report.vin}-${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
}
